name: SegnoSharp
services:
  segnosharp:
    container_name: segnosharp
    image: ghcr.io/whitestone-no/segnosharp:latest
    volumes:
      - "./data:/var/segnosharp"
      - "./music:/var/music"
    ports:
      - "8080:8080"
    environment:
      SegnoSharp_CommonConfig__DataPath: /var/segnosharp
      SegnoSharp_CommonConfig__MusicPath: /var/music
      SegnoSharp_OpenIdConnect__UseOidc: false