name: Build & Deploy Docker image
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Download Bass.NET
      run: wget https://www.un4seen.com/files/z/4/Bass24.Net.zip --directory-prefix=tmp
    - name: Unzip BASS.NET
      run: 7z e tmp/Bass24.Net.zip -o./data/bass core/Bass.Net.dll
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.3
      with:
        versionSpec: '6.x'
    - name: Execute GitVersion
      uses: gittools/actions/gitversion/execute@v3.0.3
      with:
        useConfigFile: true
    - name: Set semver variables (Prerelease)
      run: |
        echo "SegnoSharpSemVer=${{ env.GitVersion_MajorMinorPatch }}" >> "$GITHUB_ENV"
        echo "SegnoSharpSemVerFull=${{ env.GitVersion_FullSemVer }}" >> "$GITHUB_ENV"
    - name: 'Set semver variables (Release)'
      run: |
        echo "SegnoSharpSemVer=${{ env.GitVersion_MajorMinorPatch }}" >> "$GITHUB_ENV"
        echo "SegnoSharpSemVerFull=${{ env.GitVersion_MajorMinorPatch }}" >> "$GITHUB_ENV"
      if: startsWith(github.repository, 'refs/tags')
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: true
        tags: |
            ghcr.io/gthvidsten/segnosharp:${{ env.SegnoSharpSemVerFull }}
            ghcr.io/gthvidsten/segnosharp:latest  

